routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('user', 'UserController');
    Route::resource('wali', 'WaliController');
    Route::resource('santri', 'SantriController');
    Route::resource('kelompok', 'KelompokController');
    Route::resource('profile', 'ProfileController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('jadwal', 'JadwalController');
    Route::resource('spp', 'SppController');
    Route::resource('nilai', 'NilaiController');
    Route::resource('kategori-penilaian', 'KategoriPenilaianController');
    Route::get('print-nilai/{id}', 'NilaiController@print')->name('nilai.print');
    Route::resource('absensi', 'AbsensiController');
    Route::get('santri/grafik/{id}', 'SantriController@grafik')->name('santri.grafik');
});


Route::get('login-wali', function(){
    return view('auth.login-wali');
});

Route::post('login-wali', 'Auth\LoginWaliController@login')->name('login.wali');
Route::post('logout-wali', 'Auth\LoginWaliController@logout')->name('logout.wali');
Route::middleware(['auth:wali'])->group(function(){
    Route::get('dashboard-wali', 'DashboardController@indexWali')->name('dashboard.wali');
    Route::get('santri-wali', 'SantriController@index')->name('santri.wali');
    Route::get('daftar-santri', 'SantriController@create')->name('santri.daftar');
    Route::post('daftar-santri', 'SantriController@store')->name('santri.register');
    Route::get('pembayaran-spp', 'SppController@index')->name('pembayaran-spp.index');
    Route::get('tambah-pembayaran-spp', 'SppController@create')->name('pembayaran-spp.create');
    Route::post('tambah-pembayaran-spp', 'SppController@store')->name('pembayaran-spp.store');
    Route::get('lihat-jadwal', 'JadwalController@index')->name('lihat.jadwal');
    Route::get('lihat-nilai', 'NilaiController@index')->name('lihat.nilai');
    Route::get('lihat-nilai/{id}', 'NilaiController@show')->name('lihat.nilai.detail');
    Route::get('cetak-nilai/{id}', 'NilaiController@print')->name('nilai.cetak');
    Route::get('lihat-pengumuman', 'PengumumanController@index')->name('lihat.pengumuman');
    Route::get('detail-pengumuman/{id}', 'PengumumanController@show')->name('detail.pengumuman');
    Route::get('lihat-absensi', 'AbsensiController@index')->name('lihat.absensi');
    Route::get('grafik-santri/{id}', 'SantriController@grafik')->name('wali.santri.grafik');
});
Route::get('daftar', 'HomeController@daftar')->name('daftar');
Route::post('daftar', 'HomeController@store')->name('daftar.store');
Route::get('tentang-kami', 'HomeController@about');
Route::get('check-month-spp/{santri_id}', 'SppController@checkMonth')->name('check-month');

app/Kelompok.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelompok extends Model
{
    protected $table = 'kelompok';
    protected $fillable = [
        'nama',
        'keterangan',
    ];

    public static function getDefaultValues() {
        return (object) [
            'nama' => '',
            'keterangan' => '',
        ];
    }
}

app/Http/Controllers/KelompokController.php
<?php

namespace App\Http\Controllers;

use App\Kelompok;
use Illuminate\Http\Request;

class KelompokController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view ('kelompok.index', ['kelompok' => Kelompok::orderBy('nama', 'asc')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kelompok'] = Kelompok::getDefaultValues();

        return view('kelompok.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
        ]);

        Kelompok::create($request->toArray());
        return redirect()->route('kelompok.index')->with('success', 'Berhasil menambah data kelompok');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kelompok'] = Kelompok::findOrFail($id);
        return view('kelompok.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
        ]);

        Kelompok::findOrFail($id)->update($request->toArray());
        return redirect()->route('kelompok.index')->with('success', 'Berhasil mengubah data kelompok');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kelompok::findOrFail($id)->delete();
        return redirect()->route('kelompok.index')->with('success', 'Berhasil menghapus data kelompok');
    }
}

resources/views/kelompok/form.blade.php
@extends('layouts.app')

@section('title', 'Form kelompok')

@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form kelompok</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($kelompok->id)) ? route('kelompok.store') : route('kelompok.update', $kelompok->id) }}" method="post">
                    @csrf
                    @isset($kelompok->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Nama kelompok</label>
                        <input type="text" placeholder="Nama kelompok" class="form-control" name="nama" value="{{ old('nama', $kelompok->nama) }}">
                    </div>
                    <div class="form-group">
                        <label>Keterangan</label>
                        <input type="text" placeholder="Keterangan" class="form-control" name="keterangan" value="{{ old('keterangan', $kelompok->keterangan) }}">
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/kelompok/index.blade.php
@extends('layouts.app')

@section('title', 'Kelompok')

@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Kelompok</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('kelompok.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Kelompok</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Kelompok</th>
                            <th>Keterangan</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($kelompok as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama }}</td>
                                <td>{{ $row->keterangan }}</td>
                                <td>
                                    <form action="{{ route('kelompok.destroy', $row->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <a href="{{ route('kelompok.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                        <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">Belum ada data</td>
                            </tr>
                        @endforelse

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection