routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('user', 'UserController');
    Route::resource('wali', 'WaliController');
    Route::resource('santri', 'SantriController');
    Route::resource('kelompok', 'KelompokController');
    Route::resource('profile', 'ProfileController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('jadwal', 'JadwalController');
    Route::resource('spp', 'SppController');
    Route::resource('nilai', 'NilaiController');
    Route::resource('kategori-penilaian', 'KategoriPenilaianController');
    Route::get('print-nilai/{id}', 'NilaiController@print')->name('nilai.print');
    Route::resource('absensi', 'AbsensiController');
    Route::get('santri/grafik/{id}', 'SantriController@grafik')->name('santri.grafik');
});


Route::get('login-wali', function(){
    return view('auth.login-wali');
});

Route::post('login-wali', 'Auth\LoginWaliController@login')->name('login.wali');
Route::post('logout-wali', 'Auth\LoginWaliController@logout')->name('logout.wali');
Route::middleware(['auth:wali'])->group(function(){
    Route::get('dashboard-wali', 'DashboardController@indexWali')->name('dashboard.wali');
    Route::get('santri-wali', 'SantriController@index')->name('santri.wali');
    Route::get('daftar-santri', 'SantriController@create')->name('santri.daftar');
    Route::post('daftar-santri', 'SantriController@store')->name('santri.register');
    Route::get('pembayaran-spp', 'SppController@index')->name('pembayaran-spp.index');
    Route::get('tambah-pembayaran-spp', 'SppController@create')->name('pembayaran-spp.create');
    Route::post('tambah-pembayaran-spp', 'SppController@store')->name('pembayaran-spp.store');
    Route::get('lihat-jadwal', 'JadwalController@index')->name('lihat.jadwal');
    Route::get('lihat-nilai', 'NilaiController@index')->name('lihat.nilai');
    Route::get('lihat-nilai/{id}', 'NilaiController@show')->name('lihat.nilai.detail');
    Route::get('cetak-nilai/{id}', 'NilaiController@print')->name('nilai.cetak');
    Route::get('lihat-pengumuman', 'PengumumanController@index')->name('lihat.pengumuman');
    Route::get('detail-pengumuman/{id}', 'PengumumanController@show')->name('detail.pengumuman');
    Route::get('lihat-absensi', 'AbsensiController@index')->name('lihat.absensi');
    Route::get('grafik-santri/{id}', 'SantriController@grafik')->name('wali.santri.grafik');
});
Route::get('daftar', 'HomeController@daftar')->name('daftar');
Route::post('daftar', 'HomeController@store')->name('daftar.store');
Route::get('tentang-kami', 'HomeController@about');
Route::get('check-month-spp/{santri_id}', 'SppController@checkMonth')->name('check-month');

app/Jadwal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jadwal extends Model
{
    protected $table = 'jadwal';
    protected $fillable = [
        'hari',
        'jam_mulai',
        'jam_selesai',
        'keterangan',
        'user_id',
    ];

    public static function getDefaultValues() {
        return (object) [
            'hari' => '',
            'jam_mulai' => '',
            'jam_selesai' => '',
            'keterangan' => '',
        ];
    }
}

app/Http/Controllers/JadwalController.php
<?php

namespace App\Http\Controllers;

use App\Jadwal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class JadwalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view ('jadwal.index', ['jadwal' => []]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['jadwal'] = Jadwal::getDefaultValues();

        return view('jadwal.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'hari' => 'required',
            'jam_mulai' => 'required',
            'jam_selesai' => 'required',
            'keterangan' => 'required',
        ]);
        $input = $request->toArray();
        $input['user_id'] = Auth::user()->id;
        Jadwal::create($input);
        return redirect()->route('jadwal.index')->with('success', 'Berhasil menambah data jadwal');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['jadwal'] = Jadwal::findOrFail($id);
        return view('jadwal.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'hari' => 'required',
            'jam_mulai' => 'required',
            'jam_selesai' => 'required',
            'keterangan' => 'required',
        ]);
        $input = $request->toArray();
        $input['user_id'] = Auth::user()->id;
        Jadwal::findOrFail($id)->update($input);
        return redirect()->route('jadwal.index')->with('success', 'Berhasil mengubah data jadwal');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Jadwal::findOrFail($id)->delete();
        return redirect()->route('jadwal.index')->with('success', 'Berhasil menghapus data jadwal');
    }
}

resources/views/jadwal/form.blade.php
@extends('layouts.app')

@section('title', 'Form jadwal')

@section('content')
<div class="row ">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form jadwal</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($jadwal->id)) ? route('jadwal.store') : route('jadwal.update', $jadwal->id) }}" method="post">
                    @csrf
                    @isset($jadwal->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Hari</label>
                        <select name="hari" class="form-control mySelect">
                            <option value="">- Pilih Hari -</option>
                            @foreach(getHari() as $option)
                                <option value="{{ $option }}" {{ old('hari', $jadwal->hari) == $option ? 'selected' : '' }} class="text-dark">{{ $option }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Jam Mulai</label>
                                <input type="time" placeholder="Jam Mulai" class="form-control" name="jam_mulai" value="{{ old('jam_mulai', $jadwal->jam_mulai) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Jam Selesai</label>
                                <input type="time" placeholder="Jam Selesai" class="form-control" name="jam_selesai" value="{{ old('jam_selesai', $jadwal->jam_selesai) }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Keterangan</label>
                        <input type="text" placeholder="Keterangan" class="form-control" name="keterangan" value="{{ old('keterangan', $jadwal->keterangan) }}">
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/jadwal/index.blade.php
@extends('layouts.app')

@section('title', 'Jadwal')



@section('content')
<div class="row ">
    @if(Auth::guard('web')->check())
    <div class="col-12">
        <a href="{{ route('jadwal.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Jadwal</a>
    </div>
    @endif
    @foreach(getHari() as $hari)
    <div class="col-lg-4">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>{{ $hari }}</h4>
            </div>
            <div class="card-body">
                <p>Jadwal dan kegiatan hari {{ $hari }}</p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Kegiatan</th>
                            <th>Jam</th>
                            @if(Auth::guard('web')->check())
                            <th></th>
                            @endif
                        </tr>
                    </thead>
                    <tbody>
                        @forelse (getJadwal($hari) as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->keterangan }}</td>
                                <td>{{ $row->jam_mulai . ' - ' . $row->jam_selesai }}</td>
                                @if(Auth::guard('web')->check())
                                <td>
                                    <form action="{{ route('jadwal.destroy', $row->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <a href="{{ route('jadwal.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                        <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                                @endif
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">Tidak ada jadwal</td>
                            </tr>
                        @endforelse

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @endforeach
</div>



@endsection