routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('user', 'UserController');
    Route::resource('wali', 'WaliController');
    Route::resource('santri', 'SantriController');
    Route::resource('kelompok', 'KelompokController');
    Route::resource('profile', 'ProfileController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('jadwal', 'JadwalController');
    Route::resource('spp', 'SppController');
    Route::resource('nilai', 'NilaiController');
    Route::resource('kategori-penilaian', 'KategoriPenilaianController');
    Route::get('print-nilai/{id}', 'NilaiController@print')->name('nilai.print');
    Route::resource('absensi', 'AbsensiController');
    Route::get('santri/grafik/{id}', 'SantriController@grafik')->name('santri.grafik');
});


Route::get('login-wali', function(){
    return view('auth.login-wali');
});

Route::post('login-wali', 'Auth\LoginWaliController@login')->name('login.wali');
Route::post('logout-wali', 'Auth\LoginWaliController@logout')->name('logout.wali');
Route::middleware(['auth:wali'])->group(function(){
    Route::get('dashboard-wali', 'DashboardController@indexWali')->name('dashboard.wali');
    Route::get('santri-wali', 'SantriController@index')->name('santri.wali');
    Route::get('daftar-santri', 'SantriController@create')->name('santri.daftar');
    Route::post('daftar-santri', 'SantriController@store')->name('santri.register');
    Route::get('pembayaran-spp', 'SppController@index')->name('pembayaran-spp.index');
    Route::get('tambah-pembayaran-spp', 'SppController@create')->name('pembayaran-spp.create');
    Route::post('tambah-pembayaran-spp', 'SppController@store')->name('pembayaran-spp.store');
    Route::get('lihat-jadwal', 'JadwalController@index')->name('lihat.jadwal');
    Route::get('lihat-nilai', 'NilaiController@index')->name('lihat.nilai');
    Route::get('lihat-nilai/{id}', 'NilaiController@show')->name('lihat.nilai.detail');
    Route::get('cetak-nilai/{id}', 'NilaiController@print')->name('nilai.cetak');
    Route::get('lihat-pengumuman', 'PengumumanController@index')->name('lihat.pengumuman');
    Route::get('detail-pengumuman/{id}', 'PengumumanController@show')->name('detail.pengumuman');
    Route::get('lihat-absensi', 'AbsensiController@index')->name('lihat.absensi');
    Route::get('grafik-santri/{id}', 'SantriController@grafik')->name('wali.santri.grafik');
});
Route::get('daftar', 'HomeController@daftar')->name('daftar');
Route::post('daftar', 'HomeController@store')->name('daftar.store');
Route::get('tentang-kami', 'HomeController@about');
Route::get('check-month-spp/{santri_id}', 'SppController@checkMonth')->name('check-month');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama',
        'email',
        'password',
        'j_kel',
        'tempat_lhr',
        'tgl_lhr',
        'alamat',
        'no_telp',
        'level', //1 admin, 2 ustadz/ah
        'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getDefaultValues()
    {
        return [
            'nama' => '',
            'email' => '',
            'password' => '',
            'j_kel' => '',
            'tempat_lhr' => '',
            'tgl_lhr' => '',
            'alamat' => '',
            'no_telp' => '',
            'level' => '',
            'status' => '',
        ];
    }

    public function getStatus() {
        if ($this->status == "1") {
            return '<span class="badge badge-success">Aktif</span>';
        } else {
            return '<span class="badge badge-secondary">Tidak Aktif</span>';
        }
    }

    public function getLevel() {
        if ($this->level == "1") {
            return '<span class="badge badge-success">Admin</span>';
        } else {
            return '<span class="badge badge-info">Ustadz / Ustadzah</span>';
        }
    }

    public function getLevelAttribute($value) {
        return strval($value);
    }

    public function getStatusAttribute($value) {
        return strval($value);
    }

    public function formatDate() {
        $date = explode('-', $this->tgl_lhr);
        return $date[2] . '-' . $date[1] . '-' . $date[0];
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUser;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user;

    public function __construct()
    {
        $this->user = new User();
    }

    public function index()
    {
        if(Auth::guard('web')->user()->level != "1") {
            return redirect('dashboard')->with('warning', 'Gagal mengakses halaman');
        }
        return view ('user.index', ['users' => $this->user->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = (object) $this->user->getDefaultValues();

        return view('user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
    	$request['password'] = bcrypt($request['password']);
        User::create($request->toArray());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['user'] = (object) $this->user->findOrFail($id);

        return view('user.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['user'] = (object) $this->user->find($id);

        return view('user.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, $id)
    {
        $user = $this->user->find($id);
        $input = $request->all();
        if(empty($request->password)) {
            unset($input['password']);
        } else {
            $input['password'] = bcrypt($input['password']);
        }
        $user->update($input);
        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->find($id)->delete();
        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data user');
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form Admin, Ustadz, Ustadzah')



@section('content')
<div class="row ">
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form Admin, Ustadz, Ustadzah</h4>
            </div>
            <div class="card-body">
                <form action="{{ (!isset($user->id)) ? route('user.store') : route('user.update', $user->id) }}" method="post">
                    @csrf
                    @isset($user->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Nama</label>
                        <input type="text" placeholder="Nama Admin / Ustadz / Ustadzah" class="form-control" name="nama" value="{{ old('nama', $user->nama) }}">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" placeholder="Alamat Email" class="form-control" name="email" value="{{ old('email', $user->email) }}">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" placeholder="Password" class="form-control" name="password" value="">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="text" placeholder="Tempat Lahir" class="form-control" name="tempat_lhr" value="{{ old('tempat_lhr', $user->tempat_lhr) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tanggal Lahir</label>
                                <input type="text" placeholder="Tanggal Lahir" class="form-control datepicker2" name="tgl_lhr" value="{{ old('tgl_lhr', $user->tgl_lhr) }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Jenis Kelamin</label><br>
                                <label for="l">
                                    <input type="radio" id="l" name="j_kel" value="l" {{ old('j_kel', $user->j_kel) == 'l' ? 'checked' : '' }}> Laki - Laki
                                </label> &nbsp;
                                <label for="p">
                                    <input type="radio" id="p" name="j_kel" value="p" {{ old('j_kel', $user->j_kel) == 'p' ? 'checked' : '' }}> Perempuan
                                </label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>No. Telp</label>
                                <input type="text" placeholder="No. Telp" class="form-control" name="no_telp" value="{{ old('no_telp', $user->no_telp) }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" placeholder="Masukan alamat">{{ old('alamat', $user->alamat) }}</textarea>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Level</label>
                                <select name="level" class="form-control">
                                    <option value="1" {{ old('level', $user->level) == '1' ? 'selected' : '' }} class="text-dark">Admin</option>
                                    <option value="2" {{ old('level', $user->level) == '2' ? 'selected' : '' }} class="text-dark">Ustadz / Ustadzah</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Status</label>
                                <select name="status" class="form-control">
                                    <option value="1" {{ old('status', $user->status) == "1" ? 'selected' : '' }} class="text-dark">Aktif</option>
                                    <option value="0" {{ old('status', $user->status) == "0" ? 'selected' : '' }} class="text-dark">Tidak Aktif</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'Admin, Ustadz & Ustadzah')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Admin, Ustadz & Ustadzah</h4>
            </div>
            <div class="card-body">
            <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Admin, Ustadz & Ustadzah</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Level</th>
                            <th>Status</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($users as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama }}</td>
                                <td>{{ $row->email }}</td>
                                <td>{!! $row->getLevel() !!}</td>
                                <td>{!! $row->getStatus() !!}</td>
                                <td>
                                    <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <a href="{{ route('user.show', $row->id) }}" class="btn btn-sm btn-info" title="Lihat Detail"><i class="fa fa-eye"></i></a>
                                        <a href="{{ route('user.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                        <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">Belum ada data</td>
                            </tr>
                        @endforelse

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Admin, Ustadz & Ustadzah')



@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Detail Admin, Ustadz & Ustadzah</h4>
            </div>
            <div class="card-body">
                <table class="table">

                    <tr>
                        <td style="border-top: 0">Nama</td>
                        <td  style="border-top: 0">{{ $user->nama }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ $user->email }}</td>
                    </tr>
                    <tr>
                        <td>TTL</td>
                        <td>{{ $user->tempat_lhr . ', ' . $user->formatDate() }}</td>
                    </tr>
                    <tr>
                        <td>No. Telp</td>
                        <td>{{ $user->no_telp }}</td>
                    </tr>
                    <tr>
                        <td>Alamat</td>
                        <td>{{ $user->alamat }}</td>
                    </tr>
                    <tr>
                        <td>Jenis Kelamin</td>
                        <td>{{ strtoupper($user->j_kel) }}</td>
                    </tr>
                    <tr>
                        <td>Level</td>
                        <td>{!! $user->getLevel() !!}</td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td>{!! $user->getStatus() !!}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection