routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('user', 'UserController');
    Route::resource('wali', 'WaliController');
    Route::resource('santri', 'SantriController');
    Route::resource('kelompok', 'KelompokController');
    Route::resource('profile', 'ProfileController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('jadwal', 'JadwalController');
    Route::resource('spp', 'SppController');
    Route::resource('nilai', 'NilaiController');
    Route::resource('kategori-penilaian', 'KategoriPenilaianController');
    Route::get('print-nilai/{id}', 'NilaiController@print')->name('nilai.print');
    Route::resource('absensi', 'AbsensiController');
    Route::get('santri/grafik/{id}', 'SantriController@grafik')->name('santri.grafik');
});


Route::get('login-wali', function(){
    return view('auth.login-wali');
});

Route::post('login-wali', 'Auth\LoginWaliController@login')->name('login.wali');
Route::post('logout-wali', 'Auth\LoginWaliController@logout')->name('logout.wali');
Route::middleware(['auth:wali'])->group(function(){
    Route::get('dashboard-wali', 'DashboardController@indexWali')->name('dashboard.wali');
    Route::get('santri-wali', 'SantriController@index')->name('santri.wali');
    Route::get('daftar-santri', 'SantriController@create')->name('santri.daftar');
    Route::post('daftar-santri', 'SantriController@store')->name('santri.register');
    Route::get('pembayaran-spp', 'SppController@index')->name('pembayaran-spp.index');
    Route::get('tambah-pembayaran-spp', 'SppController@create')->name('pembayaran-spp.create');
    Route::post('tambah-pembayaran-spp', 'SppController@store')->name('pembayaran-spp.store');
    Route::get('lihat-jadwal', 'JadwalController@index')->name('lihat.jadwal');
    Route::get('lihat-nilai', 'NilaiController@index')->name('lihat.nilai');
    Route::get('lihat-nilai/{id}', 'NilaiController@show')->name('lihat.nilai.detail');
    Route::get('cetak-nilai/{id}', 'NilaiController@print')->name('nilai.cetak');
    Route::get('lihat-pengumuman', 'PengumumanController@index')->name('lihat.pengumuman');
    Route::get('detail-pengumuman/{id}', 'PengumumanController@show')->name('detail.pengumuman');
    Route::get('lihat-absensi', 'AbsensiController@index')->name('lihat.absensi');
    Route::get('grafik-santri/{id}', 'SantriController@grafik')->name('wali.santri.grafik');
});
Route::get('daftar', 'HomeController@daftar')->name('daftar');
Route::post('daftar', 'HomeController@store')->name('daftar.store');
Route::get('tentang-kami', 'HomeController@about');
Route::get('check-month-spp/{santri_id}', 'SppController@checkMonth')->name('check-month');

app/Santri.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Santri extends Model
{
    protected $table = 'santri';
    protected $fillable = [
        'wali_id',
        'nama',
        'tempat_lhr',
        'tgl_lhr',
        'status',
        'j_kel',
    ];

    public static function getDefaultValues() {
        return (object) [
            'wali_id' => '',
            'nama' => '',
            'tempat_lhr' => '',
            'tgl_lhr' => '',
            'status' => '',
            'j_kel' => '',
        ];
    }

    public function getStatusAttribute($value) {
        return strval($value);
    }

    public function getStatus() {
        if ($this->status == "1") {
            return '<span class="badge badge-success">Aktif</span>';
        } else {
            return '<span class="badge badge-warning">Pending</span>';
        }
    }

    public function wali() {
        return $this->belongsTo('App\Wali');
    }

    public function formatDate() {
        $date = explode('-', $this->tgl_lhr);
        return $date[2] . '-' . $date[1] . '-' . $date[0];
    }

    public function getNilai($kelompok_id) {
        return Nilai::where('santri_id', $this->id)->where('kelompok_id', $kelompok_id)->first();
    }

}

app/Http/Controllers/SantriController.php
<?php

namespace App\Http\Controllers;

use App\Absensi;
use App\Nilai;
use App\Santri;
use App\Wali;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SantriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::guard('web')->check()) {
            $santri =  Santri::orderBy('nama', 'asc')->get();
            $type = 'default';
        } else {
            $santri = Santri::where('wali_id', Auth::guard('wali')->user()->id)->orderBy('nama', 'asc')->get();
            $type = 'wali';
        }
        return view ('santri.index', ['santri' => $santri, 'type' => $type]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['santri'] = Santri::getDefaultValues();
        $data['wali'] = Wali::orderBy('nama', 'asc')->get();

        return view('santri.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'wali_id' => 'required',
            'nama' => 'required',
            'tempat_lhr' => 'required',
            'tgl_lhr' => 'required',
            'j_kel' => 'required',
        ]);

        Santri::create($request->toArray());
        if(Auth::guard('web')->check()) {
            return redirect()->route('santri.index')->with('success', 'Berhasil menambah data santri');
        } else {
            return redirect()->route('santri.wali')->with('success', 'Berhasil mendaftarkan santri, mohon menunggu persetujuan dari kami');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['santri'] = Santri::findOrFail($id);
        $data['wali'] = Wali::orderBy('nama', 'asc')->get();
        return view('santri.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'wali_id' => 'required',
            'nama' => 'required',
            'tempat_lhr' => 'required',
            'tgl_lhr' => 'required',
            'j_kel' => 'required',
        ]);

        Santri::findOrFail($id)->update($request->toArray());
        return redirect()->route('santri.index')->with('success', 'Berhasil mengubah data santri');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Santri::findOrFail($id)->delete();
        return redirect()->route('santri.index')->with('success', 'Berhasil menghapus data santri');
    }

    public function grafik($id)
    {
        $data['santri'] = Santri::findOrFail($id);
        $nilai = Nilai::where('santri_id', $id)->where('tahun', date('Y'))->get();
        $data['bulan'] = "";
        $data['nilai'] = "";
        foreach($nilai as $n) {
            $data['bulan'] .= getBulanShort()[$n['bulan']].',';
            $data['nilai'] .= $n->rataRataNilai().',';
        }

        $data['bulan'] = rtrim($data['bulan'], ",");
        $data['nilai'] = rtrim($data['nilai'], ",");

        $data['bulanya'] = date('m');
        $bulannya = date('m');

        if(request()->get('b')){
            $data['bulanya'] = request()->get('b');
            $bulannya = request()->get('b');

        }

        $data['absensi'] = Absensi::where('santri_id', $id)->whereRaw('month(tgl) = ' . $bulannya)->orderBy('tgl', 'desc')->get();


        return view('santri.grafik', $data);
    }
}

resources/views/santri/form.blade.php
@extends('layouts.app')

@section('title', 'Form santri')

@section('content')
<div class="row ">
    <div class="col-lg-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Form santri</h4>
            </div>
            <div class="card-body">
                <form action="{{  Auth::guard('web')->check() ? (!isset($santri->id)) ? route('santri.store') : route('santri.update', $santri->id) : route('santri.register') }}" method="post">
                    @csrf
                    @isset($santri->id)
                        {{ method_field('PUT')}}
                    @endisset
                    <div class="form-group">
                        <label>Nama Wali</label>
                        @if(Auth::guard('web')->check())
                        <select name="wali_id" class="form-control mySelect">
                            <option value="">- Pilih Wali -</option>
                            @foreach($wali as $option)
                                <option value="{{ $option->id }}" {{ old('wali_id', $santri->wali_id) == $option->id ? 'selected' : '' }} class="text-dark">{{ $option->nama }}</option>
                            @endforeach
                        </select>
                        @else
                            <input type="text" name="" class="form-control" readonly value="{{ Auth::guard('wali')->user()->nama }}">
                            <input type="hidden" name="wali_id" class="form-control" readonly value="{{ Auth::guard('wali')->user()->id }}">
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Nama Santri</label>
                        <input type="text" placeholder="Nama santri" class="form-control" name="nama" value="{{ old('nama', $santri->nama) }}">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="text" placeholder="Tempat Lahir" class="form-control" name="tempat_lhr" value="{{ old('tempat_lhr', $santri->tempat_lhr) }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tanggal Lahir</label>
                                <input type="text" placeholder="Tanggal Lahir" class="form-control datepicker" name="tgl_lhr" value="{{ old('tgl_lhr', $santri->tgl_lhr) }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Jenis Kelamin</label><br>
                        <label for="l">
                            <input type="radio" id="l" name="j_kel" value="l" {{ old('j_kel', $santri->j_kel) == 'l' ? 'checked' : '' }}> Laki - Laki
                        </label> &nbsp;
                        <label for="p">
                            <input type="radio" id="p" name="j_kel" value="p" {{ old('j_kel', $santri->j_kel) == 'p' ? 'checked' : '' }}> Perempuan
                        </label>
                    </div>

                    @if(Auth::guard('web')->check())
                    <div class="form-group">
                        <label>Status</label>
                        <select name="status" class="form-control">
                            <option value="1" {{ old('status', $santri->status) == "1" ? 'selected' : '' }} class="text-dark">Aktif</option>
                            <option value="0" {{ old('status', $santri->status) == "0" ? 'selected' : '' }} class="text-dark">Tidak Aktif</option>
                        </select>
                    </div>
                    @else
                        <input type="hidden" name="status" class="form-control" readonly value="0">
                    @endif

                    <div class="form-group">
                        <input type="submit" class="btn btn-primary float-right" value="Simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/santri/grafik.blade.php
@extends('layouts.app')

@section('title', 'Grafik')

@section('content')

<div class="row ">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Report Santri</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h2>Identitas Santri</h2>
                        <br>
                        <table class="table table-sm">
                            <tr>
                                <td>Nama</td>
                                <td>:</td>
                                <td>{{ $santri->nama }}</td>
                            </tr>
                            <tr>
                                <td>TTL</td>
                                <td>:</td>
                                <td>{{ $santri->tempat_lhr . ', ' . $santri->tgl_lhr }}</td>
                            </tr>
                            <tr>
                                <td>J. Kel</td>
                                <td>:</td>
                                <td>{{ $santri->j_kel }}</td>
                            </tr>
                            <tr>
                                <td>Status</td>
                                <td>:</td>
                                <td>{!! $santri->getStatus() !!}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-6">
                        <h2>Absensi Santri</h2>
                        <br>
                        <select name="bulan" id="" class="form-control bulan-option">
                            @foreach(getBulan() as $key => $option)
                                <option value="{{ $key }}" {{ $key == $bulanya ? 'selected' : '' }} class="text-dark">{{ $option }}</option>
                            @endforeach
                        </select>
                        <br>
                        <table class="table table-sm">
                            <tr>
                                <td>Tanggal</td>
                                <td>Status</td>
                                <td>Keterangan</td>
                            </tr>
                            @foreach($absensi as $row)
                                <tr>
                                    <td>{{ $row->tgl }}</td>
                                    <td>{!! $row->getAbsenStatus() !!}</td>
                                    <td>{{ $row->keterangan }}</td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-6">
                        <h2>Grafik Nilai Santri</h2>
                        <canvas id="myChart" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')

<script>
    $('.bulan-option').change(function(){
        var val = $(this).val();
        window.location.href = "{{ url()->current() }}" + "?b=" + val;
    });
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js" integrity="sha512-GMGzUEevhWh8Tc/njS0bDpwgxdCJLQBWG3Z2Ct+JGOpVnEmjvNx6ts4v6A2XJf1HOrtOsfhv3hBKpK9kE5z8AQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
const ctx = document.getElementById('myChart').getContext('2d');

bulan = "{{ $bulan }}".split(",");
nilai = "{{ $nilai }}".split(",");
console.log(bulan);
const myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: bulan,
        datasets: [{
            label: 'Rata Rata Nilai',
            data: nilai,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>

@endpush

resources/views/santri/index.blade.php
@extends('layouts.app')

@section('title', 'Santri')

@section('content')
<div class="row ">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Data Santri</h4>
            </div>
            <div class="card-body">
                @if($type == 'default')
                    <a href="{{ route('santri.create') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Tambah Santri</a>
                @else
                    <p>Berikut adalah data santri anda yang terdaftar</p>
                    <a href="{{ route('santri.daftar') }}" class="btn btn-primary btn-sm mb-4"><i class="fa fa-plus"></i> Daftar Santri Baru</a>
                @endif
                <table class="table datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Santri</th>
                            <th>TTL</th>
                            <th>J. Kel</th>
                            <th>Status</th>
                            <th>Wali</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($santri as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama }}</td>
                                <td>{{ $row->tempat_lhr . ', ' . $row->formatDate() }}</td>
                                <td>{{ strtoupper($row->j_kel) }}</td>
                                <td>{!! $row->getStatus() !!}</td>
                                <td>{!! $row->wali->nama !!}</td>
                                @if($type == 'default')
                                <td>
                                    <form action="{{ route('santri.destroy', $row->id) }}" method="post">
                                        @if(auth()->user()->level == 2)
                                            <a href="{{ route('santri.grafik', $row->id) }}" class="btn btn-sm btn-info">Report</a>
                                        @endif
                                        @csrf
                                        @method('delete')
                                        <a href="{{ route('santri.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                        <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                                @else
                                <td>
                                    <a href="{{ route('wali.santri.grafik', $row->id) }}" class="btn btn-sm btn-info">Grafik</a>
                                </td>
                                @endif
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">Belum ada data</td>
                            </tr>
                        @endforelse

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@endsection